name: root
dependencies:
- ipython=4.0.1=py27_0
- ipython-notebook=4.0.4=py27_0
- ipywidgets=4.1.0=py27_0
- jupyter=1.0.0=py27_1
- jupyter_client=4.1.1=py27_0
- jupyter_console=4.0.3=py27_0
- jupyter_core=4.0.6=py27_0
- matplotlib=1.5.0=np110py27_0
- numpy=1.10.1=py27_0
- pandas=0.17.1=np110py27_0
- scikit-learn=0.17=np110py27_1
- scipy=0.16.0=np110py27_1

